### ISSUE TITLE
export_keys also need AE with RKR

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#100]
since my implementation has been prominently featured in the "partitioning oracles paper" i was thinking that the export_key must also only be used with key-committing AE schemes. i think this should be emphasized where export_keys are mentioned in the draft.

**Comment by chris-wood** [comment]
Hmm, this is an interesting point. @hugokraw, are there key-committing restrictions for the export key in terms of how it can be used by applications?

**Comment by hugokraw** [comment]
This is a good question but the answer is no. The export key has no special restrictions except for the remark in the {#export-usage} section: _The exporter_key MUST NOT be used in any way before the HMAC value in the envelope is validated._

**Comment by chris-wood** [comment]
Thanks! I'll draft a PR that notes this in the Security Considerations.

**Comment by hugokraw** [comment]
This needs to be merged with PR 101 - see comment there.
