### ISSUE TITLE
Sigma-I signature algorithm specification

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-opaque#103]
Hello,

Sigma uses signatures, for which no algorithm has been specified in the current draft.

sku/pku can be generated and used independently from the ciphersuite used in the rest of the protocol and stored in the envelope. This would introduce one more parameter, and for Sigma only, if OPAQUE allows for that kind flexibility. From what I understand, the number of parameters is already a concern.

How should the Sigma signature algorithm be set or chosen ?

**Comment by chris-wood** [comment]
We're not specifying a wire format version of SIGMA-I, so this will need to be done in a future draft that specifies SIGMA-I. Thus, I'm closing this for now.
