### ISSUE TITLE
Simplifying envelope construction

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#120]
Here are a subset of the steps for envelope construction:

```
1. N = Unblind(blind, response.data)
2. y = Finalize(pwdU, N, "OPAQUE01")
3. rwdU = HKDF-Extract("rwdU", Harden(y, params))
4. Create SecretCredentials secret_creds with creds.skU
5. Create CleartextCredentials cleartext_creds with response.pkS
   and custom identifiers creds.idU and creds.idS if mode is customIdentifier
6. nonce = random(32)
7. pseudorandom_pad = HKDF-Expand(rwdU, concat(nonce, "Pad"), len(pt))
8. auth_key = HKDF-Expand(rwdU, concat(nonce, "AuthKey"), Nh)
9. export_key = HKDF-Expand(rwdU, concat(nonce, "ExportKey"), Nh)
...
```

Can we instead change this to:
```
3. nonce = random(32)
4. rwdU = HKDF-Extract(nonce, Harden(y, params))
5. Create SecretCredentials secret_creds with creds.skU
6. Create CleartextCredentials cleartext_creds with response.pkS
   and custom identifiers creds.idU and creds.idS if mode is customIdentifier
7. pseudorandom_pad = HKDF-Expand(rwdU, "Pad", len(pt))
8. auth_key = HKDF-Expand(rwdU, "AuthKey", Nh)
9. export_key = HKDF-Expand(rwdU, "ExportKey", Nh)
```
?

Additionally, we could consider bundling up steps 7-9 into a single HKDF-Expand call, and taking slices of that output for each of the individual variables.

**Comment by bytemare** [comment]
Replacing the static salt with the nonce, does is change any security property except added entropy ?

**Comment by kevinlewi** [comment]
Well, we are actually moving the incorporation of the nonce from steps 7-9 into step 3, so I don't think this is actually adding entropy. The only thing it accomplishes is removing the need for the static salt "rwdU".

**Comment by bytemare** [comment]
If I'm not mistaken, until now rwdu was not derived from the nonce. What I mean is that the nonce has more entropy than the string "rwdu" :)

**Comment by kevinlewi** [comment]
It is true that the rwdU will have more entropy now, but the only uses of `rwdU` in the current protocol are to be used to derive `pseudorandom_pad`, `auth_key`, and `export_key`, all of which incorporate the nonce into the HKDF. That's all I meant by saying that the overall entropy is the same.

**Comment by bytemare** [comment]
Would it therefore be necessary to keep using the nonce in these HKDF derivations ? 
The harden function could output something the length of rwdu + nonce, and that would be fed into the HKDF expansions.

**Comment by stef** [comment]
what would be the benefit of

> Additionally, we could consider bundling up steps 7-9 into a single HKDF-Expand call, and taking slices of that output for each of the individual variables.
?

**Comment by stef** [comment]
and what is the benefit of having the nonce included earlier in this procedure?

**Comment by kevinlewi** [comment]
@bytemare I think there is a security benefit to having the nonce being chosen independently of the output of the harden function, actually. It means that if a (kU, pwdU) pair were reused for multiple users, we would still get independent export keys / auth keys / pseudorandom_pads.

@stef: The only benefit is that we remove the need for a fixed string "rwdU" from this computation, and slightly simplify steps 7/8/9 to not involve concatenation of any strings.

This should not have any impact on anything except for simplicity.

Bumping this for @chris-wood / @hugokraw for comments

**Comment by stef** [comment]
simplification, and not concatenating strings is a very good reason to do this. thumbsup!

**Comment by chris-wood** [comment]
I like this suggestion a lot, with one exception: I'd prefer we keep the expand calls separate. There were, in the past, issues where the attacker played with the expand parameters to try and recover the secrets. Keeping them separate helps not reintroduce that issue.

**Comment by bytemare** [comment]
@kevinlewi I understood this :) what I meant is to not keep using the nonce in HKDF-Expand.
Like so https://github.com/cfrg/draft-irtf-cfrg-opaque/pull/126/commits/00810795fa60f5a5e77cee205d1e698d3b533077#diff-09a16f0dd79bfde63faf766f3c58ba43f6795026ce020fa36006cfec7094cf0aR642

**Comment by hugokraw** [comment]
General  comment: I appreciate that you guys add @hugokraw when discussing stuff that needs my attention. But since my attention these days is divided into so many things, please double check with me before approving any such crypto-relevant changes if I do not provide feedback.

Regarding involving the nonce into the derivation of RwdU: I am ok with it. The reason Nonce was used in the derivation of pad is for the (not too common but possible case) that someone would re-register same PwdU (and without the server changing kU), but would change the registered skU. If this happened, one would be using the same pad to encrypt two different plaintexts.  But the proposed change is correct: Once you use the nonce to modify the RwdU derivation there is no need to include the nonce in the derivation of pseudorandom_pad as long as Nonce is chosen anew each time a password is registered (or re-registered). 

Lastly, there was a comment in this thread about the nonce helping in the case of different users using the same password and same kU by the server. A server should  never use the same kU with two different users. We may want to add such remark in the security considerations and also around the place where we specify the choice of kU.

**Comment by chris-wood** [comment]
> Lastly, there was a comment in this thread about the nonce helping in the case of different users using the same password and same kU by the server. A server should never use the same kU with two different users. We may want to add such remark in the security considerations and also around the place where we specify the choice of kU.

Good idea -- I'll make a note of this and address it in a future change.

**Comment by bytemare** [comment]
`as long as Nonce is chosen anew each time a password is registered (or re-registered).`

This should be specified as well. Servers must ensure that the client doesn't reuse nonces. In practice, this means the server must retain these nonce (or a fingerprint) and validate new ones on each (re)-registration.

**Comment by hugokraw** [comment]
This needs to be specified but enforcement does not need to go all the way as you suggest. As long as the server chooses random independent keys for different users, the nonce in the envelope is of limited consequences (you only need it for the case where the user re-registers, does not change the password but chooses a new secret keys skU and the server does not change the user's OPRF key; and even then the damage of repeating or omitting the nonce is not very significant)
