### ISSUE TITLE
Change all occurrences of variable-length public/private keys to be fixed length?

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#121]
In the current version of the draft, there are occurrences such as:

```
struct {
    SerializedElement data;
    opaque pkS<1..2^16-1>;
} RegistrationResponse;
```

```
struct {
    opaque pkU<1..2^16-1>;
    Envelope envU;
} RegistrationUpload;
```

Should we change these to instead say:
```
    opaque pkS[LK];
```

where `LK` is a fixed constant dependent on the group representation?

@chris-wood

**Comment by chris-wood** [comment]
This seems fine, but I would say that `LK` is not a function of the *group*, but simply the fixed length of an AKE public key. @kevinlewi, could you please propose text?

**Comment by hugokraw** [comment]
See my comment on #132
