### ISSUE TITLE
envelope structure is not unambigious

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#122]
https://github.com/cfrg/draft-irtf-cfrg-opaque/blob/master/draft-irtf-cfrg-opaque.md#credential-types-and-envelope-construction-data-types

defines the envelope as:
```
struct {
  InnerEnvelopeMode mode;
  opaque nonce[32];
  opaque encrypted_creds<1..2^16-1>;
} InnerEnvelope;

struct {
  InnerEnvelope contents;
  opaque auth_tag[Nh];
} Envelope;
```

why is the type of `encrypted_creds` `opaque` and not `SecretCredentials` as already defined right before this?
that `encrypted_creds` is actually `SecretCredentials` is only mentioned in the following "prosa" text.

and then says this:

> auth_tag : Authentication tag protecting the contents of the envelope, covering InnerEnvelope and CleartextCredentials.

why is this `CleartextCredentials` not explicitly specified in the envelope struct?

**Comment by chris-wood** [comment]
> why is the type of encrypted_creds opaque and not SecretCredentials as already defined right before this?

`encrypted_creds` is the *encrypted* form of `SecretCredentials`

> why is this CleartextCredentials not explicitly specified in the envelope struct?

No cleartext credentials are included in the envelope -- they're only authenticated during the protocol (by being included in the MAC computation).

**Comment by stef** [comment]
hmmm. that kind of makes sense, i guess i was mislead by the previous version and the context implied by that.
