### ISSUE TITLE
Clarify OPRF mode

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#129]
OPAQUE only requires the OPRF "base" mode, which does not have evaluation verification.

**Comment by kevinlewi** [comment]
Isn't this already addressed here, at the top of the "Configurations" section:

> An OPAQUE configuration is a tuple (OPRF, Hash, MHF, EnvelopeMode). The OPAQUE OPRF protocol is drawn from the "base mode" variant of {{I-D.irtf-cfrg-voprf}}

**Comment by kevinlewi** [comment]
Closing after agreement offline with @chris-wood
