### ISSUE TITLE
Elaborate on export_key usage

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#130]
Applications can use export_key in a variety of ways (after OPAQUE completes successfully). The draft should describe some of these in more detail, perhaps in an appendix to keep the main body of text slim.

cc @rot256

**Comment by kevinlewi** [comment]
Here is one sample text that we could add to the appendix:

> The export key can be used (separately from the OPAQUE protocol) to provide confidentiality and integrity to other data which only the client should be able to process. For instance, if the server is expected to maintain any client-side secrets which require a password to access, then this export key can be used to encrypt these secrets so that they remain hidden from the server.

This only describes one application, but it is the main application that comes to mind for me.

**Comment by chris-wood** [comment]
@kevinlewi, could you throw this up in a PR? I think the proposed text is just right.
