### ISSUE TITLE
follow rfc2119 to indicate requirement levels

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#143]
rfcs generally refer and use https://tools.ietf.org/html/rfc2119 to define requirement levels. this spec should follow that tradition diligently.

**Comment by chris-wood** [comment]
RFC2119 [is already cited](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#section-1.1) for the purposes of requirement and normative language.

**Comment by stef** [comment]
aaah. i didn't see this in the source markdown file.
