### ISSUE TITLE
Agree on a consistent format for all "magic string" constants

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#157]
Here is a list of all of the constant strings currently specified in the protocol:

Strings relating to envelope construction:
- "Pad"
- "AuthKey"
- "ExportKey"

Strings relating to the AKE section:
- "3DH"
- "client mac"
- "handshake secret"
- "server mac"
- "handshake enc"
- "encryption pad"
- "session secret"
- "OPAQUE "

Strings coming from the VOPRF draft (out of scope for this draft, but here for reference):
- "VOPRF06-HashToGroup-"
- "VOPRF06-Finalize-"

Can we agree on a convention for all of these strings?

Here's my proposal: I say we change all of them (except for the VOPRF ones obviously) to look like "AuthKey", "HandshakeSecret", "SessionSecret", and to remove the space at the end of "OPAQUE ".

**Comment by bytemare** [comment]
+1 for CamelCase and space deletion

**Comment by chris-wood** [comment]
+1 as well!

**Comment by bytemare** [comment]
For OPAQUE defined strings, how about this:

Envelope construction:
- "OPAQUE-HashToScalar"
- "Pad"
- "AuthKey"
- "ExportKey"
- "MaskingKey"
- "PrivateKey"
- "OprfKey"
- "CredentialResponsePad"

Strings relating to the AKE section:
- "3DH"
- "OPAQUE-" _(note the dash in lieu of the space, I believe this will lead to fewer implementation mishaps)_
- "ClientMac"
- "ServerMac"
- "SessionSecret"
- "EncryptionPad"
- "HandshakeEnc"
- "HandshakeSecret"

**Comment by bytemare** [comment]
Currently, the list of HashTo* DST's used are:

| Designation | Value  | Used in | Defined in|
| ------------- | ------------- | ------------- | ------------- |
| ku h2s | nil | CreateRegistrationResponse(), CreateCredentialResponse() | / |
| skc h2s | "OPAQUE-HashToScalar" | DeriveAkeKeyPair() | OPAQUE  |
| password h2c | ? | VOPRF/Blind() | [VOPRF](https://github.com/cfrg/draft-irtf-cfrg-voprf) |
| masking key h2s | ? | VOPRF/DeriveKeyPair()| [VOPRF](https://github.com/cfrg/draft-irtf-cfrg-voprf) |
| oprf finalize | ? | VOPRF/Finalize() | [VOPRF](https://github.com/cfrg/draft-irtf-cfrg-voprf) |

("?" for now as they are still being discussed in [#236](https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/236) and [#244](https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/244).)

It could be useful to have them all listed in a section of the document and refer to them by constants in the functions where they are used.

**Comment by chris-wood** [comment]
@bytemare, @kevinlewi: I think we can close this now that #174 landed with the right strings. Strings used in the OPRF functions can be resolved in that document (as needed).

**Comment by bytemare** [comment]
I updated the list above, for reference. I think we can close
