### ISSUE TITLE
Test vectors: client_public_key should be an intermediate value

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#176]
In all of the test vectors, client_public_key is under "Input Values", but it should be an "Intermediate Value" instead.

cc: @chris-wood

**Comment by chris-wood** [comment]
This is only true in internal mode. It's an input otherwise. Can you please send a PR to fix?

**Comment by kevinlewi** [comment]
I see, I thought this would be true of external mode, given the following current text:


> External Key mode {#external-mode}
> This mode allows applications to import custom keys for the client. This specification only imports the client's private key and > internally recovers the corresponding public key. Implementations are free to import both and thus spare a scalar multiplication at registration. In this case, the functions FinalizeRequest(), CreateEnvelope(), and BuildInnerEnvelope() must be adapted accordingly.

Perhaps we should also update that to make it more clear that both client_private_key and client_public_key are inputs in external mode?

**Comment by chris-wood** [comment]
The private key is all that's necessary, I think. That text says that APIs can let clients import the public key, too. That's totally up to the implementation. I'm not sure off hand what further clarification is needed, so can you send a PR?

**Comment by kevinlewi** [comment]
Sure, just want to clarify the change exactly since I think I am slightly confused by the above statements:

> This is only true in internal mode. It's an input otherwise.

This seems to indicate that client_public_key for external mode *should* remain as an input for the test vectors section

> The private key is all that's necessary, I think. ... I'm not sure off hand what further clarification is needed,

This seems to indicate that client_public_key for external mode *should not* remain as an input for the test vectors section

Which should it be?

**Comment by bytemare** [comment]
I agree that the pubkey _can_ be checked as an intermediate value. For the external mode, even if it's given it will eventually pop back up and can be tested the same way as for the internal mode.

In the internal mode, it will **always** be an intermediate value, and **sometimes** in the external mode.

**Comment by chris-wood** [comment]
> In the internal mode, it will always be an intermediate value, and sometimes in the external mode.

This. :-)
