### ISSUE TITLE
Should all Credential fields be encrypted?

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#20]
Some fields, like the user public key, might only require authentication.

**Comment by hugokraw** [comment]
Authenticating-only the server's public key can be beneficial in a setting where the server uses the same public key with multiple clients. Encrypting the key means a larger envelope stored as *each*  user's record while authenticating-only makes both the envelope and per-user shorter shorter. There is some savings in not having to decrypt the server's public key but this seems negligible (especially if the authentication operation that cannot be avoided is more expensive than decryption).

**Comment by chris-wood** [comment]
This was resolved in #36.
