### ISSUE TITLE
Add implementation considerations section

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#200]
This should probably include, among other things, how to implement each routine in constant time (in the user secret parameters), and why that's important.

**Comment by kevinlewi** [comment]
Two more items to consider adding:
1) Ensuring that all secrets are zero'd/cleared upon deallocation, both on the client and server side,
2) Timing attacks for the "faked credential response", an implementation needs to be very cautious when branching on whether or not a registered password file for the user exists

**Comment by chris-wood** [comment]
@kevinlewi would you be able to prep a PR for this?
