### ISSUE TITLE
Add deployment considerations section

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-opaque#204]
Like #173 but for deployments, as there are specificities to OPAQUE that implementations can't always cover and that users of the protocol should or must consider.

An incomplete list would include:

- Given the client-enumeration mitigation constraints
  - applications must use the same configuration during their lifecycle (including the client records)
- The OPRF seed is not just a global salt and must be given particular care regarding its secrecy and longevity
- credential_identifiers and client_identifiers MUST be unique amongst all clients of the app

**Comment by chris-wood** [comment]
@bytemare can you please take this and prepare a PR?

**Comment by chris-wood** [comment]
(oops)

**Comment by bytemare** [comment]
Nah, I think we can close it. It's more or less the same the other issue :)
