### ISSUE TITLE
Comment around encrypted credentials text

### ISSUE THREAD

**Issue by claucece** [cfrg/draft-irtf-cfrg-opaque#221]
The description of OPAQUE reads:

```
OPAQUE consists of two stages: registration and authenticated key exchange. In the first stage, a client registers its password with the server and stores its encrypted credentials on the server.
```

I really like this description but it might not be completely accurate as, as far as I understand, in the Internal mode, no encrypted credentials are stored, as the the client's private and public keys are deterministically derived from the OPRF output. Might be good to note that if what I'm saying is indeed correct ;)

**Comment by chris-wood** [comment]
No encrypted private key is stored, but the user's envelope is still stored, so this seems accurate as-is.

**Comment by bytemare** [comment]
I understand that the word "encrypted" seems not relevant in the context of the internal mode. Do you have a suggestion for the wording @claucece ?

**Comment by claucece** [comment]
@chris-wood yes. The only thing that is stored from the client, I guess, in the end, is the `client_identity`; which is really nice as one can argue that in the internal OPAQUE mode the server only has the id of the client and nothing beyond that.

@bytemare I can try to create a PR for it. Maybe after IETF? Don't want to push this with the meeting so soon...

**Comment by chris-wood** [comment]
> @chris-wood yes. The only thing that is stored from the client, I guess, in the end, is the client_identity; which is really nice as one can argue that in the internal OPAQUE mode the server only has the id of the client and nothing beyond that.

Well, the server stores an entire `RegistrationUpload` struct.

If we really think a change is warranted here, we could say something like, "... stores its credentials on the server in such a way that knowledge of the secret password is required to access them," or whatever. 🤷
