### ISSUE TITLE
Protect the client record with a KEM on registration

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-opaque#240]
Currently, the client sends a masking key during registration for the server to obfuscate login messages and protect against client enumeration. This relatively sensitive and secret piece of data requires the full registration to be "secure" with integrity, authenticity, and confidentiality, as offered by TLS for example.

Integrity and authenticity cannot be subverted once the session is over and past. Confidentiality, however, is not ensured if encryption keys are backed up, shared, or leaked, and allows decryption after the session (e.g. proxy re-encryption, logging, legal compliance, etc.). The masking key is at risk of being revealed to a passive (even non-malicious) attacker after registration has happened.

This risk can be avoided by using a KEM to protect the last registration message from the client to the server. Implementations could leverage the fact the client gets the server public key in the registration response and use symmetric encryption using a basic KEM. We could either build it into OPAQUE (not that expensive, as it happens only once) or add it to the security considerations.

**Comment by bytemare** [comment]
@chris-wood I was thinking that using the HPKE-like base mode could be sufficient here, and use the registration transcript, identities, and configuration as context/aad. I don't think it's too complex to add here unless another dependency is problematic (though that spec is rather mature). What do you think?

**Comment by chris-wood** [comment]
I don't think we should make anything specific here, as it's a consideration external to the protocol. I'd just say that clients can encrypt their records for servers using HPKE, full stop.

**Comment by bytemare** [comment]
Alright 👍

**Comment by bytemare** [comment]
Let's fold this into #310
