### ISSUE TITLE
MHF usage

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#245]
OPAQUE currently assumes that the MHF output is pseudorandom, as it's currently used as the IKM input to the KDF:

```
randomized_pwd = Extract("", Harden(y, params))
```

We could fix this by requiring the MHF to output something that's pseudorandom, or by changing how we invoke Extract, e.g.:

```
randomized_pwd = Extract(Harden(y, params), y))
```

cc @cjpatton, @hugokraw

**Comment by hugokraw** [comment]
Extractors output pseudorandom values by definition. The implicit assumption here is that the MHF does not reduce the computational entropy of y, a reasonable assumption for a MHF (one can add a remark on this in the security considerations section). We can keep the current specification (*). Moreover, the second option violates a principle of extractors that the salt should be independent of the IKM. 
(*) I prefer the convention that when there is no salt, HKDF is called with salt=0 not salt="". Can you change that (also in other cases where "" is used as salt)?

**Comment by chris-wood** [comment]
> Extractors output pseudorandom values by definition. The implicit assumption here is that the MHF does not reduce the computational entropy of y, a reasonable assumption for a MHF (one can add a remark on this in the security considerations section). We can keep the current specification (). Moreover, the second option violates a principle of extractors that the salt should be independent of the IKM.

Well, imagine the following Harden variant:

```
Harden(x, params) = 0^31 || SHA256(x)[0] // LSB of the hash
```

As written in the spec, this would satisfy the definition of Harden, but clearly is not great. Do we need to be more specific about what Harden outputs here, with respect to its inputs? (We can also clarify that Extract does not reduce the entropy of its inputs, but that seems separate to me.)

> () I prefer the convention that when there is no salt, HKDF is called with salt=0 not salt="". Can you change that (also in other cases where "" is used as salt)?

salt="" is convention adopted by RFC8446 and other documents, so I think we should keep it as-is.

**Comment by hugokraw** [comment]
We can either require that Harden(x, params) does not reduce entropy of x, or (to be on the safe side) define 

randomized_pwd = Extract("", y || Harden(y, params)))
where || stands for concatenation

as for salt="", I was confused by TLS 1.3 that uses the symbol 0 to denote "".
How does "" look as a string of bits when input into the HMAC key?

**Comment by chris-wood** [comment]
Augmenting the call to Extract seems simpler to me, so let's go with that 👍
