### ISSUE TITLE
Configuration agreement

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#246]
The configurations section is the first place where client/server agreement on configurations is noted. We should promote this to an earlier part of the draft, and make clear that configuration negotiation is _not_ part of the protocol. (That would be done by any wrapper protocol, for example.)

**Comment by chris-wood** [comment]
> Should it be negotiated, though

I don't believe so. That would add a tremendous amount of complexity to the protocol.

**Comment by bytemare** [comment]
Agreed :)

**Comment by bytemare** [comment]
Ah, I missed the "_not_" part on my first read 🤦‍♂️

But yes, we can emphasize earlier in the document that even a wrapper protocol should not implement negotiation on login.
