### ISSUE TITLE
Client public key leakage

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#248]
Should the client public key leak to the server (on the wire) during the AKE protocol? Should we allow this to happen, or should it not be permissible with any AKE? 

cc @hugokraw

**Comment by hugokraw** [comment]
I am confused. Doesn't the server store the client's public key? Why would this be a "leak"? Anyway, the client's public key does not require secrecy protection at all (from the server or anyone else), except for privacy considerations. But I am probably misinterpreting your question

**Comment by chris-wood** [comment]
> Doesn't the server store the client's public key? 

Indeed! However, consider the case where an attacker is masquerading as the server during authentication. (The attacker doesn't have the public key -- only the envelope, which it can get directly from the real server.) Would it be a problem if the AKE forced the either client or server to send, over the wire, the public key? Can the adversary use this in any way to confirm a password guess? 

As an example, if the OPRF would be honestly evaluated by the real server and client, and the client revealed its public key, would this allow faster dictionary attacks by the adversary? I don't immediately see how, but it seems an interesting edge case?

**Comment by hugokraw** [comment]
It's not a problem. Remember that OPAQUE is the composition of an OPRF and *any* (secure) AKE. So if the AKE is secure when the public key is completely public, then OPAQUE is secure also when the public key is disclosed to anyone. This is the case for all AKEs we are dealing with: 3DH, HMQV, SIGMA and any "public key AKE" where a public key is... well... public.

**Comment by chris-wood** [comment]
ACK -- closing!
