### ISSUE TITLE
Internal mode private key seed length

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#249]
The seed used to derive the private key in internal mode is currently `Nsk`:

```
seed = Expand(randomized_pwd, concat(nonce, "PrivateKey"), Nsk)
```

If `Nsk` is large for the AKE, then this seed may be quite large, too. We probably don't need anything beyond 32 bytes of randomness here, regardless of the AKE protocol. Perhaps we drop `Nsk` here and just use a constant? Or introduce another constant instead?

The same question might also be asked of the `ikm` derivation:

```
ikm = Expand(oprf_seed, concat(credential_identifier, "OprfKey"), Nok)
```

cc @hugokraw

**Comment by bytemare** [comment]
Isn't there a hash-to-curve requirement for this input length ?

**Comment by chris-wood** [comment]
These are both hashing to scalars (currently), but even if that were the case, it's possible for other AKEs to _not_ use hash-to-curve stuff.

**Comment by hugokraw** [comment]
You can define the seed to always be 256 bits which has sufficient entropy for any cryptographic use. The DeriveAuthKeyPair function will need to deal with the fact that the length is "only" 256 bits. In particular, if the procedure requires more bits than that, it will first stretch the seed to a longer string using some PRG or PRF. (Does that answer the question?)

**Comment by chris-wood** [comment]
Yep, that matches my suggestion in the issue description. I'd be fine with just pinning 32B here. @kevinlewi, thoughts?
