### ISSUE TITLE
Abstract the login messages

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-opaque#254]
Currently, login messages look like that
```
KEx {
  struct Credential_Something;
  ake_thing_a;
  ake_thing_b;
  etc.
}
```

For the sake of abstraction and modularity, I suggest we define these without AKE specificities. Like this:

```
KEx {
  struct Credential_Something;
  struct AKE_things;
}
```

From an editorial point of view, we can therefore define all the external OPAQUE components outside any specification (OPRF + internal/external mode + AKE in this case)

**Comment by chris-wood** [comment]
@bytemare can we close this?
