### ISSUE TITLE
Add note on security consideration on server-side online guessing attacks

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#264]
We should add a remark about the fact that online guessing attacks (against any Asymmetric PAKE) can be done from the client side and from the server side.

**Comment by kevinlewi** [comment]
Also, we could consider adding as a deployment consideration the ability to incorporate the client identity alongside the password to be input to the OPRF. This provides client-side entropy, which in the event that a client is interacting with a malicious server, could be beneficial.

**Comment by bytemare** [comment]
Integrating the ID with the password as input results in having to re-register if the ID changes. This can be done programmatically though, and I don't think it's a big problem.

**Comment by chris-wood** [comment]
@kevinlewi can you please send a PR for this?
