### ISSUE TITLE
Security Recommendation: dual CSPRNG

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-opaque#266]
The TLS 1.3 RFC ([appendix C.1](https://datatracker.ietf.org/doc/html/rfc8446#appendix-C.1)) suggests using separate CSPRNGs to generate public and private values.

It could be interesting to add a similar recommendation.

In OPAQUE, I think the only public values are nonces (public keys are derived from private keys, so they don't count). Is there anything else?

**Comment by chris-wood** [comment]
@bytemare will you have time for this? If not, I can do it.

**Comment by bytemare** [comment]
Not immediately. If you'd like to do it, go for it :)

**Comment by bytemare** [comment]
We already require the CSPRNG to be good, and it doesn't seem necessary to add this complexity to the spec and implementations if the main CSPRNG is not reliable.
