### ISSUE TITLE
Forward secrecy in KE3

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-opaque#267]
In `# Online Authenticated Key Exchange {#online-phase}` we say

> , and ke3 provides explicit client authentication and
> full forward security (without it, forward secrecy is only achieved against eavesdroppers,
> which is insufficient for OPAQUE security).

how is the ke3 client mac contributing to forward secrecy? Or is this not relevant anymore?

cc @hugokraw

**Comment by hugokraw** [comment]
It is relevant. Without client authentication in KE3, the attacker can choose a value x and send in the first message, the value g^x. Assume the server, sends ke2 and starts using the session_key to encrypt confidential information targeted to the client. If in the future, the attacker learns the server's private key or the password, then it learns the session key. This breaks forward secrecy. Note that the protocol with ke1 and ke2 provides forward secrecy against passive attackers (eavesdroppers) but the above shows that it does not provide FS against an active attacker. Does this make sense?

**Comment by bytemare** [comment]
Very clear! I haven't thought about this scenario and was stuck with passive attacks. Thank you very much for your explanation 😃
