### ISSUE TITLE
Add a section called Setup

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-opaque#289]
Just like any other protocol, there is some preparation steps that must be done (off--line) before to run a protocol.

I suggest including a section called Setup, enumerating all the steps and premises required by this phase.

This was already suggested: 

> I feel a lack of a section called Setup, like any other protocols has.

_Originally posted by @armfazh in https://github.com/cfrg/draft-irtf-cfrg-opaque/pull/286#discussion_r751954650_

**Comment by chris-wood** [comment]
This content is already included in the text, so what specifically is the request here?
