### ISSUE TITLE
Using HKDF-Expand in deriving KEYS

### ISSUE THREAD

**Issue by hugokraw** [cfrg/draft-irtf-cfrg-opaque#29]
Instead of  KEYS = HKDF(salt=0, IKM=k, info="EnvU", Length=L1+L2+L3) one could do 
KEYS = HKDF-Expand(key=k, info="EnvU", Length=L1+L2+L3)
which makes more sense since k is already a pseudo random key, we would only need to specify that k is the length of an HMAC key.

**Comment by chris-wood** [comment]
This is done in #36.
