### ISSUE TITLE
Agree on the name of the second phase of the protocol

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-opaque#290]
The protocol has two phases Registration and Online Authentication.

The main piece of the Online Authentication phase is an Authenticated Key Exchange (AKE). but it is not the only piece.

The current title for the section explaining Online Authentication is  "Online Authentication Key exchange". However, I suggest the name should be "Online Authentication" as this section is in charge to describe not only the AKE but also how the AKE is invoked and how the state is managed. 

--
See more discussion at: 

_Originally posted by @armfazh in https://github.com/cfrg/draft-irtf-cfrg-opaque/pull/286#discussion_r751957364_

**Comment by chris-wood** [comment]
The output of the protocol is (1) a session key for both client and server, and (2) an export key for the client. I think renaming this to "Online Authentication" misses (1). I'm not sure of a phrase that encompasses both (1) and (2), but I agree that something more clear would be useful.

**Comment by armfazh** [comment]
It may work to move Section 10.4 (https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#name-export-key-usage) right after the `Online Authenticated Key Exchange.` 

So the message that the document must convey is that the output of the protocol is a session key and a secondary key that can be used by the client. Document might hint use cases for this secondary key.

**Comment by bytemare** [comment]
The section you're mentioning already hints at a use case for the export key. Are you saying there should be more or a different example?

Also, this section is referenced at the beginning of the Online Authenticated Key Exchange section. Does that fit with your suggestion?

**Comment by armfazh** [comment]
> The section you're mentioning already hints at a use case for the export key. Are you saying there should be more or a different example?

the example is good, but I consider it appears too late in the document.

 
> Also, this section is referenced at the beginning of the Online Authenticated Key Exchange section. Does that fit with your suggestion?

Rather than making a reference, what about moving Sec 10.4 to the place where it is referenced?

**Comment by armfazh** [comment]
Also, on a second thought the title seems correct.
