### ISSUE TITLE
Determine the content of client/server states during online authentication

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-opaque#291]
Currently the state is vaguely specified. Specification must be clearer in what is the content of the state. 
(this may need some minor fixes, but still needs to be addressed).

Raised after:

_Originally posted by @chris-wood in https://github.com/cfrg/draft-irtf-cfrg-opaque/pull/286#discussion_r751669794_

**Comment by armfazh** [comment]
So, either formally specifying what the state contains, or removing at all the state structure are both good alternatives. Currently, it is specified something in between.

**Comment by bytemare** [comment]
I suggest we define a generic structure in the first part of the spec
```
struct {
  OPRFState oprf;
  AKEState ake;
} ClientState;
```

Then, for whatever is chosen for the OPRF or AKE, it must define its own `OPRFState` and `AKEState`. In a later section, where ze specify each part, we can define
```
struct {
  string password;
  uint8 data[Nsk];
} OPRFState ;
```

and
```
struct {
  uint8 client_secret[Nsk];
  KE1 ke1;
} AKEState ;
```

**Comment by chris-wood** [comment]
We only need to specify the structure of protocol messages, not implementation specific structures and related state. Using standard OO (dot style) notation for this state seems most clear.

**Comment by kevinlewi** [comment]
I would be in favor of removing the mentioning of these states altogether, and to just push the modification of these states into the inputs and outputs for each function. That way, each function can be seen as stateless.

**Comment by chris-wood** [comment]
@kevinlewi I think we'll find that the parameter list for these functions will grow to an unreadably large size, but it's worth removing all mentions of state to at least see how it looks!
