### ISSUE TITLE
Update algorithm

### ISSUE THREAD

**Issue by daxpedda** [cfrg/draft-irtf-cfrg-opaque#294]
Re-hashing is sometimes practiced with traditional password hashing mechanisms. The main concern here is that when a user doesn't log-in for years, it prevents the server from updating the algorithm used to hash the password, which can only be done when the user logs in again.

The solution is usually to re-hash hashes, basically wrap hashes in another hash, on client authentication both hash's have to be performed, afterwards the hash can be updated.

Obviously that isn't really possible with OPAQUE, as we don't actually store a hash. The `RegistrationUpload` is secured by the `server_private_key` instead.

I also noticed, that the only recommendation what to do in the event of server compromise in the draft, is to also resample the `oprf_seed`.

So I was thinking that we can kill two birds with one stone, if we can specify a mechanism to update the `RegistrationUpload` by using a new (and stronger) `server_private_key`, we have provided a mechanism to allow upgrading `RegistrationUpload` to newer algorithms and also provide a (hopefully) good response tactic if the `server_private_key` is compromised.

Warning: I'm no cryptographer and only have a surface-level understanding of everything I'm talking about here!

**Comment by bytemare** [comment]
Hi @daxpedda, do you have a suggestion to do that?

**Comment by daxpedda** [comment]
I don't, but I plan to look into it.

Thinking about this more, we may want to open a separate issue addressing what is actually compromised and what attack vectors this would open up if the `server_private_key` or `oprf_seed` or both are compromised.

**Comment by chris-wood** [comment]
cc @hugokraw for his thoughts

**Comment by kevinlewi** [comment]
I think this feature would be nice to have, but is almost certainly not supported by OPAQUE, since it is not as simple as "password onion hashing" (tacking on stronger hashing algorithms). Instead, implementers should consider a migration from an old `server_private_key` or `oprf_seed` to a newer one upon future client login, by re-running the registration protocol with the new key material.

At any rate, I believe this is outside of the scope of the specification.

**Comment by hugokraw** [comment]
I haven't seen this before (if you ask for my feedback and I don't respond it is good to ping me...). I think that the solution in all these cases is to let the user login with the old parameters, then reset the password and re-run registration with the new keys and/or mechanisms. If the old parameters are not available or compromised one can reset the password without a login.  Measures against user enumeration may be required for this process too.

**Comment by daxpedda** [comment]
> Measures against user enumeration may be required for this process too.

This is the main reason I was asking this, because I don't know how that would be done.

The only thing that comes to mind is to have every user on login run the process through all possible ciphersuites at the same time, so if they have old credentials they can still authenticate and then update the ciphersuite, while still preventing user enumeration.
