### ISSUE TITLE
Shared Secret Derivation: `SerializePublicKey`

### ISSUE THREAD

**Issue by daxpedda** [cfrg/draft-irtf-cfrg-opaque#295]
While reviewing a P-256 implementation of OPAQUE-3DH I noticed that there is a difference between it and "common" ECDH. When using ECDH usually only the x-coordinate is used to derive the secret. That isn't the case in OPAQUE-3DH apparently.

Looking over the spec I discovered the function `SerializePublicKey`, which is used on top of DH. I couldn't find any reference to it otherwise, what is it supposed to do?

I'm no cryptographer, forgive me if this question seems naive.

**Comment by chris-wood** [comment]
@daxpedda for reference, can you please point to the implementation you're referencing? It's true that we somehow dropped the definition of `SerializePublicKey`. Let's use this issue to track adding that back. 

@kevinlewi, can you please take this?

**Comment by daxpedda** [comment]
Reference: https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-6.4.3.2-2.

**Comment by bytemare** [comment]
The commit that deleted the definition is [this one](https://github.com/cfrg/draft-irtf-cfrg-opaque/commit/deae8d8d3a72ccde19ae9b553da1c77b35f1d8d3). The definition was deleted as the function wasn't used.

Good catch! We should definitely bring that back.
