### ISSUE TITLE
`DeriveAuthKeyPair` can fail

### ISSUE THREAD

**Issue by daxpedda** [cfrg/draft-irtf-cfrg-opaque#298]
`DeriveAuthKeyPair` is supposed to take a randomly generated seed and return a private and public key. As far as I understand `HashToScalar` doesn't guarantee to return a non-zero scalar, yielding an invalid private key.

I'm no cryptographer, so here are the assumptions that I made:
- `HashToScalar` returns a non-zero scalar.
- A zero scalar is an invalid private key for the key exchange mechanism.

If this is correct, how should failure be handled? Considering this is happening on the client, I believe constant-time isn't an issue and it could just try again with a different seed?

**Comment by daxpedda** [comment]
I've recently seen an implementation that does reduces by MODULUS - 1, and then adds one. In any case, thinking about it more I'm not sure if this should be addressed here or in VOPRF.

**Comment by daxpedda** [comment]
According to VOPRF, their `DeriveKeyPair` is also supposed to produce a non-zero scalar. Again, it relies on `HashToScalar` to do that, which as far as I can tell it doesn't.
https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-voprf-08#section-2.1
> Two functions can be used for generating a (V)OPRF key pair (skS,
pkS) **where skS is a non-zero integer** less than p and pkS =
ScalarBaseMult(skS): GenerateKeyPair and DeriveKeyPair.

So it seems to me that `HashToScalar` should really return a non-zero scalar and this should be addressed in VOPRF, right?

**Comment by armfazh** [comment]
For example, the key generation for ECDSA (https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf) admits two methods:
rejection sampling (non-constant time) and reduction mod n-1 plus one: `d = (c mod (n–1)) + 1`.
Thus, it is guaranteed to produce non-zero scalars (private keys).


For OPAQUE/VOPRF, the key generation could adopt something similar. However, note that the HashToScalar method must not be the target for changes, we want HashToScalar returns 0 since it's a valid scalar, but not a valid key.

Also, there is a negligible probability that HashToScalar returns 0. This may be the reason why, in practice, the current key generation method works without issues.

**Comment by daxpedda** [comment]
> For example, the key generation for ECDSA (https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf) admits two methods: rejection sampling (non-constant time) and reduction mod n-1 plus one: `d = (c mod (n–1)) + 1`. Thus, it is guaranteed to produce non-zero scalars (private keys).

Thank you, I wasn't aware that the method I mentioned above is actually standardized somewhere.
> For OPAQUE/VOPRF, the key generation could adopt something similar. However, note that the HashToScalar method must not be the target for changes, we want HashToScalar returns 0 since it's a valid scalar, but not a valid key.

So in VOPRF we will have to adjust `DeriveKeyPair` and in OPAQUE `DeriveKeyPair` and `DeriveAuthKeyPair`. I believe this covers all?
> Also, there is a negligible probability that HashToScalar returns 0. This may be the reason why, in practice, the current key generation method works without issues.

I am aware. It's just that in the Rust implementations I'm working on these sort of invariants are enforced on a type level (which is amazing ofc), so the only reason why I noticed this issue is because I couldn't infallibly convert a `Scalar` to a `PrivateKey` type.

I'm still unsure what is necessary to "fix" for example `DeriveKeyPair` in OPAQUE if we don't intend to touch `HashToScalar`:
```
1. private_key = HashToScalar(seed, dst="OPAQUE-DeriveKeyPair")
2. public_key = ScalarBaseMult(private_key)
3. Output (private_key, public_key)
```
Just put a step between 1 and 2 to fail if `private_key` is zero? Or should we just insert a function that makes sure to reduce it to something non-zero, like the one you mentioned above: `d = (c mod (n–1)) + 1`?

**Comment by daxpedda** [comment]
> For OPAQUE/VOPRF, the key generation could adopt something similar.

Sorry, so what you are proposing is basically:
```
DeriveKeyPair(seed)

Steps:
1. scalar = HashToScalar(seed, dst="OPAQUE-DeriveKeyPair")
2. private_key = (scalar mod (n - 1)) + 1
3. public_key = ScalarBaseMult(private_key)
4. Output (private_key, public_key)
```

**Comment by chris-wood** [comment]
Since `DeriveAuthKeyPair` is run with a client-chosen envelope nonce, I suggest we instead treat invalid scalars as an exceptional case and require clients to retry with a new nonce. Same for servers when deriving the OPRF key pair.

**Comment by daxpedda** [comment]
What about `DeriveKeyPair`?

**Comment by chris-wood** [comment]
@daxpedda right, we'd do the same for `DeriveKeyPair`, which is what I meant when I said "same for servers when deriving the OPRF key pair."

**Comment by chris-wood** [comment]
I think we can fold this into #312. Closing as such.
