### ISSUE TITLE
KdKey rationale 

### ISSUE THREAD

**Issue by hugokraw** [cfrg/draft-irtf-cfrg-opaque#30]
We need to add the rationale for KdKey somewhere. Can use the following as a basis:

The main use case I have in mind is retrieving a non-OPAQUE encrypted credential. Namely, expanding the use of OPAQUE with a credential-retrieval functionality. You could always put additional stuff in the envelope but I would prefer to restrict the envelope with its OPAQUE-specific functionality. In addition, having a separate encrypted credential can achieve several properties: allowing the server to send it only after the user authenticated; send it under the session key with forward secrecy; allowing the addition of a credential to the user's record after registration; allowing the use of non-RKR encryption for credential encryption; and just giving better extensibility, flexibility and separation from the core OPAQUE protocol.

**Comment by chris-wood** [comment]
This is sort of like the TLS exporter secret. I'll see if I can write it as such!

**Comment by chris-wood** [comment]
@hugokraw do you think the current rationale is sufficient? If not, would you mind proposing text to improve (expand) it?

**Comment by hugokraw** [comment]
I assume you mean the text under {export-usage}.
I think it is ok.
It may be a good idea to add the following (which I have in my draft):
There is no restriction for the type of encryption scheme
   used in this case.  However, ExportKey MUST NOT be used in any way
   before the HMAC value in EnvU is validated.
