### ISSUE TITLE
Concat and structs

### ISSUE THREAD

**Issue by BjoernPetersen** [cfrg/draft-irtf-cfrg-opaque#304]
The definition for `concat` says:

> `concat(x0, ..., xN)`: Concatenate byte strings. For example, concat(`0x01`, `0x0203`, `0x040506`) = `0x010203040506`.

But if I understand correctly, in all functions defined in [section 4](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#name-key-recovery) and in [CreateCredentialResponse](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-6.3.2.2) it's used to concatenate byte strings and structs (namely `CleartextCredentials` and `Envelope`).

Am I assuming correctly that the values within the structs should be concatenated in order of declaration? In any case, this should probably be clarified.

**Comment by bytemare** [comment]
Hi Björn,

Indeed, serialization of a struct is the concatenation of its elements in the order of their position within the struct.

We take the notation from RFC8446, as indicated, and SerDe should follow that. I agree though that an additional phrase for clarification wouldn't hurt.

**Comment by bytemare** [comment]
Actually, the structures are specifically indicated as being in wire format in the document, which defines how they are serialized.

**Comment by chris-wood** [comment]
Correct. Structs are wire format messages -- byte strings -- so concat works on them like any other message. Closing as such. @BjoernPetersen, please reopen if you think further clarification is needed.

**Comment by yandi-banyu** [comment]
Sorry I am quite new and currently practicing to read and implement a protocol. I'd like a further clarification please. I assume this is how to do serialization of nested struct? (example from the [6.4.2.1 Transcript Functions - Preamble](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#name-transcript-functions))

```ts
interface CredentialRequest {
  blindedMessage: Uint8Array
}

interface AuthRequest {
  clientNonce: Uint8Array
  clientPublicKeyshare: Uint8Array
}

interface KE1 {
  credentialRequest: CredentialRequest
  authRequest: AuthRequest
}

concat(..., KE1, ....)
```

Is it like this? (for every new struct level, we compute the total length of the nested struct recursively)

```ts
concat(..., concat(os2ip(credentialRequest.byteLength,2), credentialRequest, os2ip(authRequest.byteLength,2), authRequest), ...)
concat(..., concat(os2ip(credentialRequest.byteLength,2), concat(os2ip(blindedMessage.byteLength, 2), blindedMessage)), ...authRequest, ...)
```

Or this? (flattening it)

```ts
concat(..., concat(os2ip(blindedMessage.byteLength, 2), blindedMessage), concat(os2ip(clientNonce.byteLength, 2), clientNonce), concat(os2ip(clientPublicKeyshare.byteLength, 2), clientPublicKeyshare), ...)
```

**Comment by stef** [comment]
none of the members of structs are prefixed by their length these are all known in advance, and not needed for serialization and transport over the network. the prefixing with length is only used for the transcript. you might want to also store a length of the identity variables, since they can be <1..2^16>, but that is really also up to you, if ascii only i guess you could also use pascal strings. also the spec doesn't really say how you serialize things, you might pack the structs into json, or encode them with baseN, this is out of scope of the spec. as an example this is already as far as it gets with specification of serialization: https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#section-6.1

hope this helps

**Comment by yandi-banyu** [comment]
Yes, after a good rest from it everything clicked and I was able to check against the test vector. I guess I was just tired. Sorry for the inconvenience!
