### ISSUE TITLE
Test cases for edge cases and failing conditions

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-opaque#309]
It would be interesting to provide values, test vectors, and expected behavior for edge cases and conditions we expect the protocol and implementations to return errors. This will help implementors evaluate some security properties to a certain degree.

We could draw a first list of some of these values and testing functions (e.g. invalid points). This goes well in hand with #256

**Comment by bytemare** [comment]
Pinged the VOPRF team in https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/333 to see if such vectors are planned for the OPRF scope.

**Comment by kevinlewi** [comment]
We will implement these test vectors for the three error types in the Error Considerations section (one for each).

**Comment by kevinlewi** [comment]
Closing this since it was also closed in https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/333
