### ISSUE TITLE
Failure handling

### ISSUE THREAD

**Issue by daxpedda** [cfrg/draft-irtf-cfrg-opaque#312]
Currently it is not specified how to handle failures that aren't the fault of implementation, user or host (in the case of the usual authentication process).

The question on all the following points is:
- What should be done in the case of a failure:
  - Is it okay to just try again with a different input, for example in the case of randomness that caused the failure.
  - Should simply an error be emitted and the process started from scratch again.
- Should something be adjusted in the VOPRF spec to not produce an error.

This is a list of functions that can fail:
- [`CreateRegistrationRequest`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-5.2.1-1) can fail because it uses [`Blind`](https://www.ietf.org/archive/id/draft-irtf-cfrg-voprf-08.html#section-3.3.3.1-1), which can produce the identity point. I don't know if this is a problem or not, see cfrg/draft-irtf-cfrg-voprf#305. The easiest solution is to simply try again as the failure depends on RNG.

- The same applies to [`CreateRegistrationRequest`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-5.2.1-1).

- [`CreateRegistrationResponse`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-5.2.2-1) can fail because it uses [`Evaluate`](https://www.ietf.org/archive/id/draft-irtf-cfrg-voprf-08.html#section-3.3.1.1-1), which can simply fail with [`InverseError`](https://www.ietf.org/archive/id/draft-irtf-cfrg-voprf-08.html#section-5.1-2.3). In this case `CreateRegistrationResponse` can't be completed, unless a new `oprf_seed` is generated, or users receive an error and have to start from [`CreateRegistrationRequest`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-5.2.1-1) again.

- [`CreateCredentialResponse`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-6.3.2.2-3) can't fail, because otherwise `CreateRegistrationResponse` should have failed before, it might be helpful to mention that.

- [`CreateRegistrationResponse`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-5.2.2-1), which can fail because of [`DeriveKeyPair`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-2.1-5), which can fail if `HashToScalar` returns a zero scalar. See #298.

- [`CreateCredentialResponse`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-6.3.2.2-3), which can fail because of [`DeriveKeyPair`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-2.1-5), which can fail if `HashToScalar` returns a zero scalar. See #298.

- [`FinalizeRequest`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-5.2.3-2), which can fail because of [`Store`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-4.1.2-2), which can fail because of [`DeriveAuthKeyPair`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-6.4.2-4), which can fail if `HashToScalar` returns a zero scalar. See #298.

- [`RecoverCredentials`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-6.3.2.3-1) can't fail, because otherwise `FinalizeRequest` should have failed before, again, it might be helpful to mention that.

**Comment by daxpedda** [comment]
I addressed some of the issues that relate to VOPRF here too: https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/307.

**Comment by bytemare** [comment]
That's some of what #256 tries to address: document falling/errors scenarios :)

I'm preparing a PR around which to articulate the discussion on how to do that. Your input will be greatly appreciated 👍

**Comment by bytemare** [comment]
I agree that we should work to avoid having errors in functions where they can be avoided. I believe that the errors you mention relative to HashToScalar and DeriveKeys are being worked upon in VOPRF, e.g. see https://github.com/cfrg/draft-irtf-cfrg-voprf/pull/308

**Comment by daxpedda** [comment]
In the end I would like to avoid any errors that require the whole protocol to be restarted even if every party involved did everything correctly (e.g. didn't produce invalid public keys).

Producing an error like this makes it hard to control how library consumers will react. Most likely the user would simply receive an error saying "Unexpected Error", instead of library consumers just implementing a way to automatically try again.

So I think the solution provided in cfrg/draft-irtf-cfrg-voprf#308 is perfect because introducing the counter makes it basically infallible. Though of course I would prefer a solution that is constant-time and truly infallible much more, like simply  doing reduction mod n-1 plus one, like proposed here: https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/298#issuecomment-1006936162.

I would also like to clarify something. Some of the failures I mentioned above are not currently handled by the spec at all. [`CreateRegistrationRequest`](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-5.2.1-1) for example doesn't actually check if `Blind` produces an identity point. But maybe that is also something that is best handled in the VOPRF spec.

**Comment by chris-wood** [comment]
Looking at this based on latest developments, here's my summary of things:

- CreateRegistrationRequest (and CreateCredentialRequest) can fail if Blind fails. This is an exceptional event that happens with negligible probability. We should simply note that it occurs and recommend that implementations require clients to change passwords
- CreateRegistrationResponse can currently fail if DeriveKeyPair fails. We can fix that by recommending that the implementation choose a new credential identifier and re-run this step. This happens with negligible probability, too. Alternatively, the protocol could generate the credential identifier and output it, but that might complicate the interface.
- FinalizeRequest can currently fail if DeriveAuthKeyPair in Store() fails. We can fix this by recommending that implementations choose a new envelope_nonce in this event. 

With these changes, the corresponding authentication steps should not fail. Does this look right?

**Comment by Tronic** [comment]
It would be best to specify it as such that `DeriveKeyPair` cannot fail. Namely, depending on the curve different methods should be used to ensure that suitable non-zero scalar (secret key) is produced no matter what the random bytes. In particular with Ed25519 the RFC requires masking off bit 255 and masking on bit 254, such that no identity can ever be created (it also masks off the three lowest bits such that scalar multiplication always results in points in the prime subgroup even if the original point was in one of the normally never used 7 other subgroups). The mod n-1 plus 1 clamping works with prime order curves.

In blinding one can similarly clamp `k` and `r` but not r's inverse. This should ensure that the points created are well-behaving and there can be no errors unless either the client or the server maliciously pass invalid values. Checking of points for correctness is slow and difficult, so whether that is necessary needs some thought (also pointing out that different curves again have different requirements).
