### ISSUE TITLE
include metadata about MHF in envelope

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-opaque#337]
currently the memory hard function (MHF) and its parameters are hard-coded in the ciphersuite, however if a user wants to use a different MHF, it would be possible to made parameters available as part of envelope's metadata.

cc: @evanderkoogh , who may want to add more comments.

**Comment by chris-wood** [comment]
We've discussed this in the past and concluded that supporting negotiation of key stretching parameters via the envelope is not worth the complexity. (I don't have the relevant issue at hand, but we could probably dig it up.) Another complicating factor is that there's no registry for key stretching algorithms, so this would require us to introduce one.

**Comment by kevinlewi** [comment]
See https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/69 which contains the aforementioned discussion. Closing this issue but feel free to reopen if there are new points to be made!
