### ISSUE TITLE
does the authorization mac check really have to be constant time?

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#341]
```
def ServerFinish(ke3):
  if !ct_equal(ke3.client_mac, state.expected_client_mac):
```
each run of the protocol must use different macs anyway, so if an attacker learn how many bytes they managed to match, does not help them at all.

also i was wondering i saw, that in contrast to earlier variants, now the session key is only considered valid if this check is successful, but the paper and earlier drafts also allowed for implicit authentication in case the session key is used for setting up an encrypted channel for example, what happened to that?

**Comment by kevinlewi** [comment]
cc: @hugokraw in case he can help with answering about:
1) the necessity for the constant-time mac checks here, and
2) considering the session key as valid only if this mac check succeeds.

**Comment by stef** [comment]
thx for reviving this

**Comment by hugokraw** [comment]
Stef is right that the MAC in the KE protocol (particularly 3DH) is "one time" in the sense that the MAC key is used only for this particular run of the protocol so there is no need to protect the key for repeated/long-term uses.
He is also right that if you forgo the check of the MAC, the session key is still implicit authenticated. MAC verification does provide value in the form of explicit authentication, key confirmation and forward security against active attackers. If you don't need these properties the KE protocol is still secure without the MAC.

**Comment by kevinlewi** [comment]
Thanks for chiming in @hugokraw!

@stef: Is your question mainly out of curiosity, or are you proposing that the requirements for the specification be changed to not require this mac check to be constant-time?

It seems to me that since implementations already have to make constant-time checks in other parts of the protocol, and so the cost/burden of doing this for the mac check is negligible, even if it is extraneous. So I would advocate for still keeping the constant-time requirement in there for simplicity of exposition.

Or alternatively, we could add a small note saying that this last check isn't required to be in constant-time, into the draft text.

**Comment by stef** [comment]
> @stef: Is your question mainly out of curiosity, or are you proposing that the requirements for the specification be changed to not require this mac check to be constant-time?

i'm sorry, for mixing up two things:

1/ yes the constant timeness of the check is just out of curiosity, since i noticed it is unnecessary i just wanted it to be confirmed if i'm right about this.

2/ the question if the mac is necessary at all is another one. and that is less out of curiosity. without the mac, an attacker can check for correctness by checking the mac, without the mac, an attacker needs (at least) one more step to confirm the success of a guess at a correct password. and in some cases i think that is actually a good thing that improves security of the password. which is weird, not doing a mac having a positive effect. but i guess it's similar to having a mac of the plaintext of some otp encrypted message, it reduces the security level from information theoretic to computational. at least that is what i was thinking, maybe i'm wrong.

**Comment by stef** [comment]
actually i'm not quite sure about this anymore it was quite some time ago i was wondering about this and i might not get all things right anymore regarding 2/.

**Comment by hugokraw** [comment]
In OPAQUE, the attacker learns if it guessed the password correctly by verifying the MAC computed on the envelope so omitting the server's MAC from the key exchange does not help.

**Comment by stef** [comment]
uh. thank you for this lesson. /o\
