### ISSUE TITLE
Remove Nseed in favor of Nok everywhere

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#359]
It's one less constant and the result would be the same. I think I'd be fine with this change. @kevinlewi, @bytemare: thoughts?

**Comment by bytemare** [comment]
So as the keyspace of decaf is higher than that of ristretto, it means that it goes as well (32 to 56), which would be a different value than for now (but for what we have not provided test vectors). It sounds indeed reasonable to me have a longer seed in these cases!

**Comment by chris-wood** [comment]
Yeah, I mean, anything longer than 32 is really overkill for security, but it might simplify implementations and help readability if there are less constants.

**Comment by chris-wood** [comment]
On reflection, this seems like it would be confusing in practice, as some seeds we derive are totally unrelated to keys. Let's keep this as-is.
