### ISSUE TITLE
OPAQUE-3DH config and example are inconsistent

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#370]
in https://github.com/cfrg/draft-irtf-cfrg-opaque/blob/master/draft-irtf-cfrg-opaque.md#configurations-configurations
says the following:
> An OPAQUE-3DH configuration is a tuple (OPRF, KDF, MAC, Hash, KSF, Group, Context) ....

and then a few lines below that this:

> Absent an application-specific profile, the following configurations are RECOMMENDED:

>    OPRF(ristretto255, SHA-512), HKDF-SHA-512, HMAC-SHA-512, SHA-512, Scrypt(32768,8,1), internal, ristretto255
>    OPRF(P-256, SHA-256), HKDF-SHA-256, HMAC-SHA-256, SHA-256, Scrypt(32768,8,1), internal, P-256

the next to last tuple member `internal` is inconsistent with the first quoted line, instead the group should be listed here. and i'm not quite sure if it is correct for the context, for me this is confusing, what is this `internal` and how this relates - if at all - to the context.

**Comment by kevinlewi** [comment]
Sorry for the confusion. I believe this "internal" string should be omitted. It was introduced in https://github.com/cfrg/draft-irtf-cfrg-opaque/commit/950f2f0586dd03a2b3ffab11008c21a4d0d3f12b back when there was an "external" and "internal" mode for the envelope configuration portion of the protocol. Now that we no longer have those, we should have removed this internal configuration reference, but failed to.

**Comment by bytemare** [comment]
Indeed! Good catch 👍
