### ISSUE TITLE
why keyshare why not ephemeral key pairs?

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#371]
I'm confused by the term keyshare, this term doesn't tell me anything, and i think it obscures the nature of this value, the keyshare is nothing but an ephemeral key pair, and if we would call it that i think understanding would be easier.

maybe you use keyshare because it's a more generic term that applies to other opaque instantiations, but the current spec focuses on 3dh where the keyshare is really an ephemeral  keypair, please lets call it that.

**Comment by kevinlewi** [comment]
Hi @stef, thanks for the feedback. Can you clarify what exactly would be the proposed change here? I believe we use keyshare to refer to one half of the keypair, not the keypair itself. (keyshare = public component, private_keyshare = private component).

At the moment, there are the following four variables that have "keyshare" in their name:
- `server_keyshare`
- `client_keyshare`
- `server_private_keyshare`
- `client_private_keyshare`

Are you suggesting that we alter these variable names? And if so, do you have a proposal for what these variables should be renamed to?

The terminology "key share" only appears as prose in the text in 3 locations (unless I missed some):
1) In the definition of client_keyshare: "A serialized client ephemeral key share of fixed size `Npk`."
2) In the definition of server_keyshare: "Server ephemeral key share of fixed size `Npk`, where `Npk`
depends on the corresponding prime order group."
3) In the last paragraph of the "SIGMA-I instantiation sketch" section: "[...] would use only the ephemeral key shares exchanged between client and server"

Are you proposing that we just replace "ephemeral key share" here with "ephemeral public key"?

Thanks in advance for any clarifications!

**Comment by bytemare** [comment]
The term _keyshare_ or _key share_ is a common term in Diffie-Hellman-protocol-like literature to designate the participants' key material that they share with each other.

**Comment by stef** [comment]
> Are you proposing that we just replace "ephemeral key share" here with "ephemeral public key"?

this! please! :)
