### ISSUE TITLE
Return values of the Recover and RecoverCredentials functions

### ISSUE THREAD

**Issue by stsch9** [cfrg/draft-irtf-cfrg-opaque#384]
The _ClientFinish_ function (Section 6.2.3) needs the _client_public_key_ if the _client_identity_ is empty. However, the _client_public_key_ is calculated in the _Recover_ function (Section 4.1.3). 
Would it therefore make sense that both the _Recover_ function and the _RecoverCredentials_ function (Section 6.3.2.3) return the _client_public_key_ so that it can also be used for the _AuthClientFinalize_ function (_client_identity_ = _client_public_key_ if _client_identity_ is empty)?

**Comment by bytemare** [comment]
That's what I actually do in my implementation. I makes sense to add it in the spec if it helps :)

**Comment by stsch9** [comment]
Thank you very much for the feedback. You are also welcome to close the issue.

**Comment by chris-wood** [comment]
@bytemare are you still able to send a PR for this?
