### ISSUE TITLE
Is server private key used in AKE protocol?

### ISSUE THREAD

**Issue by mitar** [cfrg/draft-irtf-cfrg-opaque#391]
In [6. Online Authenticated Key Exchange](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#name-online-authenticated-key-exc) it is listed that `server_private_key` is input to the AKE protocol, but in [10.12. AKE Private Key Storage](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#name-ake-private-key-storage) it says:

> Server implementations of OPAQUE do not need access to the raw AKE private key.

Do do server implementations need a private key or not? Or is this not the same private key and is something else?

**Comment by bytemare** [comment]
The answer to your question should be in the rest of the paragraph.

A server implementation could delegate operations with the AKE private key to a dedicated backend. The protocol doesn't need raw access to the private key (in contrast with the public key) but needs "something" to perform the AKE on its behalf, like using an HSM for example.

**Comment by mitar** [comment]
I see. Thanks.
