### ISSUE TITLE
Migration to a new protocol version, hash, etc.

### ISSUE THREAD

**Issue by mitar** [cfrg/draft-irtf-cfrg-opaque#394]
With regular password based authentication when the client sends the password to the server over TLS connection, migration to new ways of storing passwords is relatively easy: on successful login you migrate the user to new version or new hash, etc. Completely transparent to the user/client.

I am trying to understand how can this be done with OPAQUE. For example, how to bump hash complexity or pick a new hash? It looks like client would have to do that in some way (similar to #392).

Should a description of steps here be documented in the spec? Some recommended practice?

Maybe the solution is to always do both registration and login, which would probably address this, #392, and #388. In a way this is what sending plaintext password is: you can register the user, login the user, or even both at the same time, with the same type of a message (username and password) to the server.

**Comment by daxpedda** [comment]
See https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/294 for some previous discussion.

**Comment by stef** [comment]
if your question is regarding password hashing, the server is completely indifferent what algo you use to hash your password for password hardening. you can use whatever password hashing algo and difficulty you prefer, the server has absolutely no clue about what you're doing. changing either of these is the same problem as changing the password itself, the client needs to do a re-registration.

**Comment by mitar** [comment]
Yes, I understand that client fully controls that. What I would probably I like is to is in the spec a protocol for:

> the client needs to do a re-registration

So it probably means client first does login with old protocol/hash version and then re-registration with a new one. But are there any security considerations here so that server could not be tricked into doing something bad? Like how you tie the login with registration? Are messages around this something which should be standardized or is this left completely to the implementer to implement? I just worry that I would miss something and that this would open a security hole. Maybe this is not something which has to be in the spec, but only in client library implementations, providing an easy API to do this.

**Comment by mitar** [comment]
For example, it would be neat if protocol would include "force re-registration" flag in messages or something. So that if the server is compromised, one could start issuing that on login to communicate to client libraries do do re-registration.

**Comment by mitar** [comment]
I agree here, for most of this a good library could handle handling this. I think the only thing left is if there are needs for messages to include some version, or some other flags, which would help client libraries do the right thing and if we should standardize those?

**Comment by bytemare** [comment]
What version are you thinking about?

Also, users are free to embed a standard OPAQUE message into another one including a version, e.g.
```
struct {
  OPAQUEMessage bytes;
  Version string;
  SomethinElse string;
} KE2;
```

The spec doesn't have a notion of versioning in the protocol, yet, and I don't know whether it will. That's why it's left out.

But remember there are Ciphersuite identifiers, that specify different parameters. Would that answer your need for versioning?
