### ISSUE TITLE
2 factor authentication

### ISSUE THREAD

**Issue by stsch9** [cfrg/draft-irtf-cfrg-opaque#410]
Many applications have the requirement to offer a 2 factor authentication.
Would it be possible to integrate 2 factor authentication directly into the Opache protocol. 
A suggestion:
Instead of deriving the per-client seed (the seed used to derive per-client OPRF keys) with
```
seed = Expand(oprf_seed, concat(credential_identifier, "OprfKey"), Nok)
```
(see [Section 5.2.2)](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#section-5.2.2) the server chooses a random seed per client:
```
seed = random(Nok)
```
The server has a secret key to encrypt the seed and sends the encrypted seed to the client during offline registration, so that the client cannot decrypt the seed. The server does not store the encrypted seed.

This means: The client has to know its password and send the encrypted seed to the server to authenticate successfully.

I am aware that the client has to store the encrypted seed. Also, the encrypted secret must be distributed to all devices of the client. This is not very user friendly.

For example, to combine Opache with TOTP authentication, i think TOTP authentication should be performed first, followed by Opache authentication, since the export key and the session key should be known at the end of the authentication process.

**Comment by kevinlewi** [comment]
In OPAQUE, the setting is that the client only needs to know the password (and no other information) to be able to authenticate and complete the login step. So unfortunately I don't think that this mechanism that you describe would be incorporated directly into the OPAQUE protocol.

**Comment by stsch9** [comment]
Thank you for the answer. Of course you are welcome to close the issue.
