### ISSUE TITLE
detecting password change

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#412]
In a new paper by Hao et all https://eprint.iacr.org/2023/768 in the 3rd argument for designing an alternative for OPAQUE is the following:

> 3) After OPAQUE was selected by IETF, it was discovered that the original protocol reveals information to passive observers about whether the password has been recently changed during a login session [16]. Although this revelation may at first appear minor, it can be of significant concern in practice. Recall that the main motivation for augmented PAKE is to address the threat of “server com- promise”. In principle, with the stolen credentials from a compromised server, the attacker is able to launch brute-force attacks to uncover plaintext passwords, but this is a time-consuming process. If a user diligently updates the password, her account on the server can remain secure. However, many users may be slow to update passwords. By passively monitoring the login sessions for all users, an attacker learns valuable information to identify those who have not changed the password and hence prioritizes the brute-force attack against those users. SPR-6a does not appear to have this problem.

i looked up the reference, which is a paper by Hao https://eprint.iacr.org/2021/839 - i was unable to find this issue on a quick skimming. and i am not sure i can immediately pinpoint where such an information leak would be possible in the current draft during the login.

i think others might stumble on this paper and wonder if and how this is considered in the draft, so it might be prudent ;) to address this issue, perhaps in the security considerations?

**Comment by kevinlewi** [comment]
We call this attack "client enumeration", and it was indeed missing from the original protocol, but since then we have addressed it: see related issues #183, #210 for instance.

We also have the subsection on Client Enumeration in the draft, which is already included within the Security Considerations section. So I think we've more or less addressed it, falling short of explicitly making a reference to the paper in the draft.

Will let others chime in with their thoughts, but I'd be in favor of closing this issue without modification to the current draft.

**Comment by kevinlewi** [comment]
We define "client enumeration" differently. From the doc:

Client enumeration refers to attacks where the attacker tries to learn extra information about the behavior of clients that have registered with the server. There are two types of attacks we consider:
- An attacker tries to learn whether a given client identity is registered with a server, and
- An attacker tries to learn whether a given client identity has recently completed registration, re-registered (e.g. after a password change), or changed its identity.

I believe the second bullet point is exactly referring to what was quoted, no?

**Comment by stef** [comment]
hmm, ok. if the doc defines it like this. it's a bit confusing to deviate from the normal interpretation. but i guess it's ok. maybe put a footnote to the paper in the issue that the spec as is does not have the problem that is listed in that paper?

**Comment by kevinlewi** [comment]
Right, so in regards to adding a footnote with a link to the paper, I am not sure if we should essentially set the precedent that any paper in the future which claims a weakness in OPAQUE is something that we should mention that we have addressed in the spec.

I'm in favor of not mentioning the paper, but will also let others chime in. @chris-wood , @bytemare

**Comment by stef** [comment]
hmmm, you do have a good point with this "not making a precedent". i agree.
