### ISSUE TITLE
lengths of elements

### ISSUE THREAD

**Issue by hugokraw** [cfrg/draft-irtf-cfrg-opaque#43]
Who, when and how determines  the length of elements to be generated or received. For example, how does the client know what the value of Nk should be. More significant how does the client know Nk or len(pt) when receiving the envelope?

On a related note, for a derivation like
SK, Km2, Km3, Ke2, Ke3 = HKDF(salt=0, IKM, info, L)
we need to assume that the client knows how to parse the key stream correctly and uniquely hence it needs to know the lengths of each key.  This is also needed even if we compute a separate HKDF-Expand for each value (since Expand requires to define a length value). How does the client know these values, are these determined by the specific algorithms or ciphersuite ? Should this information be part of the information authenticated by the envelope or some other mechanism?
How does TLS 1.3 deals with this, namely, how it communicates and authenticates the ciphersuite/algorithms/version?

**Comment by chris-wood** [comment]
> Who, when and how determines the length of elements to be generated or received. For example, how does the client know what the value of Nk should be. 

This is part of the configuration. We should define this!

> More significant how does the client know Nk or len(pt) when receiving the envelope?

The length of the envelope's ciphertext is equal to len(pt), so the client uses that to determine the length of the pad.

On the length of keys, they're all `Nk` bytes long, which is part of the configuration. I'll throw up a PR that defines this. Unlike TLS, I don't think we want to negotiate the ciphersuite in-band.

**Comment by hugokraw** [comment]
The ciphersuite needs to be set and fixed at registration time and it needs to be learned by the client during login.  If this information is wired into the client implementation/configuration then no need to worry about it. But otherwise, we need care (e.g., if the client is a browser contacting a server for which the client does not have configuration information).
The OPRF needs to be known or guessed before getting the envelope (similar to key_share algorithms in TLS 1.3). Do we need to have a mechanism for the server to say, please use this other OPRF if the guess was incorrect? Should we worry about downgrade attacks?
For the envelope the client needs to know what hash to use (how does it learn that?). If the OPRF and hash used by the client are correct, then we can trust the MAC computed on the envelope to detect any manipulation of the envelope. 
And then there is the AKE ciphersuite that needs to include the AKE protocol type itself (SIGMA, 3DH, etc)  and the specific algorithms/curves used by the AKE implementation. But the latter can be encoded into the envelope itself and verified by the MAC.

**Comment by hugokraw** [comment]
How does the client parse/differentiate ciphertext and auth_data? I assume this is defined by the Envelope struct, but I don't know how these things are implemented. DO they have special separators, length values, etc.? I am worried about possible attacks that play with the boundaries of these elements.

**Comment by chris-wood** [comment]
> How does the client parse/differentiate ciphertext and auth_data? I assume this is defined by the Envelope struct, but I don't know how these things are implemented. DO they have special separators, length values, etc.? I am worried about possible attacks that play with the boundaries of these elements.

Indeed! Clients know to parse the ciphertext and auth_data in sequence (by the struct's definition), and know how to parse the type and length of each element in these lists. Everything should be unambiguous.
