### ISSUE TITLE
Serialization of Diffie-Hellman output to allow use of HSM protected keys

### ISSUE THREAD

**Issue by Razumain** [cfrg/draft-irtf-cfrg-opaque#444]
Diffie-Hellman operations using HSM protected keys can potentially be used both in the OPRF function as well as in the 3DH Key-Exchange Functions.

In OPRF a DiffieHellman operation can be used on top of the current evaluated element

The function `BlindEvaluate(oprf_key, blinded_element)` can be voluntarily extended by the server to:

`DiffieHellman( ks, BlindEvaluate(oprf_key, blinded_element))`

This simply adds another scalar multiplication to the evaluated element, which can be unblinded by the client blind inverse.

The only thing that stands in the way of this operation, is the inclusion of the Y coordinate in the result when the corresponding DiffieHellman only produce the X coordinate as result.

The same is true for the 3DH key Exchange Functions which could be fully compatible with HSM protected keys if the shared secret was the X coordinate only instead of a full point serialization.

**Comment by stef** [comment]
for previous discussion on this see #238

**Comment by Razumain** [comment]
> for previous discussion on this see #238

It seems to me that these discussions both adress HSM usage, but adress very different issues.

NIST SP 800-56A establishes that the shared secret from Diffie-Hellman Z = xP where xP is the x-coordinate of P.
This is not in harmony with how Diffie-Hellman shared secret is specified in Opaque and effectively blocks performing Diffie-Hellman operations in a HSM that operates according to SP 800-56A.

In addition to this. I see a lost opportunity to use a HSM Diffie-Hellman operation to evaluate the blinded password

- the client hashes an input to a curve using hash-to-curve > point p on the curve
- the client blinds that point with an ephemeral scalar b using scalar multiplication > p^b
- the servers uses the oprf secret scalar o to evaluate that, using scalar multiplication > p^(b . o)
- the servers uses a (possibly) long term secret scalar k to evaluate that, using scalar multiplication via a HSM Diffie-Hellman operation > P = p^(b . o . k) ==> Z = xP
- the client unblinds that using scalar multiplication with the modular inverse (it's noted 1/b) on the compressed point P' = 1|xP > P'^1/b ==> x-coordinate of  p^(o . k)

This does work at least for P256 and it seems to work also for 25519, but I have to verify that better in tests.

It is all made available by discarding the Y component in 2 places of the spec:

1. As the used shared secret in 3DH
2. As the unblinded element in the OPRF Finalize function:

That is if:

  hashInput = I2OSP(len(input), 2) || input ||
              I2OSP(len(unblindedElement), 2) || unblindedElement ||
              "Finalize"

Instead would be:

  hashInput = I2OSP(len(input), 2) || input ||
              I2OSP(len(xP of unblindedElement), 2) || xP of unblindedElement ||
              "Finalize"


I know this is a big ask, that quite possibly is too much of a change to accommodate. But If there would be any clever way to at least allow this us of a HSM without breaking the standard, that would be very valuable.

**Comment by Razumain** [comment]
I would like to revert my proposal here.

Mathematically and conceptually it works wonders, but given that this is build into OPRF, I think the right way to go, if you use HSM is to recover the missing Y.

Illary provided a great solution for how to do that with the cost of en extra DH operation with the HSM:

>- Have HSM output x(aB) and x(a(B+G)).
>- Guess Z=aB from first HSM output.
>- Calculate x coordinate of Z+A, where A is your public key.
>- Check if that is consistent with the second HSM output.

So we should not do this for OPRF. If you want to do this in OPRF you simply have to do this trick to recover Y.

For the use of DH in 3DH AKE it might still be worth considering only using the X coordinate to be compatible with off the shelf DiffieHellman operations based on PrivateKey objects (rather than raw scalar multiplication).

Finally, a note about this would be great in the OPAQUE draft to point out that the solution above is possible if you want to extend the security of the OPRF with an HSM protected scalar.

**Comment by kevinlewi** [comment]
Hi @Razumain, after reading through the context here, I'm glad to hear that there is a way to make this work, but am currently not seeing a good way to reference this in the draft. Am I also understanding correctly that this is specific to the curve point representation and would not apply to ristretto255 points (or would it)?

If you have any recommended language that you would like to add to the draft, it would be great if you could take a stab at it :)

**Comment by kevinlewi** [comment]
Closing this as it seems to have been resolved.

**Comment by daxpedda** [comment]
Just stumbled on this issue while doing some HSM implementation work in [`opaque-ke`](https://crates.io/crates/opaque-ke). There are no issues implementing Diffie-Hellman with Curve25519, e.g. PKCS#11s `CKM_ECDH1_DERIVE` returns the correct point, I guess simply because of the nature of Curve25519.

However, this is different with NIST curves. PKCS#11s `CKM_ECDH1_DERIVE` only returns the X-coordinate, as described by OP. While it is possible to recover the Y-coordinate, its even/oddness can't. One solution with the current spec I've been using until now is to just present both to the client, which then can find out which one works for them. IANA cryptographer, but I assume this isn't actually a security issue.

If the spec could accommodate somehow for this it would be nice. But if not, it should at least include some language in the [AKE Private Key Storage](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-18.html#name-ake-private-key-storage) section, like @kevinlewi suggested:
> In practice, HSMs don't support Diffie-Hellman, but ECDH, which only returns the X-coordinate with NIST curves. The Y-coordinate can be recovered, but not its oddness, yielding two possible Y-coordinates. While it is possible to present the client with two possible `server_mac`s and deduce the correct point from there, it is instead recommended to use Curve25519 as the AKE algorithm when using HSMs.

**Comment by daxpedda** [comment]
I missed this:
> Illary provided a great solution for how to do that with the cost of en extra DH operation with the HSM:
> 
> > * Have HSM output x(aB) and x(a(B+G)).
> > * Guess Z=aB from first HSM output.
> > * Calculate x coordinate of Z+A, where A is your public key.
> > * Check if that is consistent with the second HSM output.

Just tried it out and I can confirm it works. Although doubling the HSM operations is not ideal.

Here is my updated suggestion:
> In practice, HSMs don't support Diffie-Hellman, but ECDH, which only returns the X-coordinate. With Weierstrass curves, the Y-coordinate can be recovered with a second ECDH operation. Therefor it is recommended to use Curve25519 as the AKE algorithm when using HSMs, where the recovery of the Y-coordinate comes naturally as part of deserializing the ECDH output.
