### ISSUE TITLE
rename Evaluate() to Contribute()

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#53]
since github does not support reviewing markdown documents i'm submitting this as an issue:

The OPRF primitive defines a 
```
Evaluate(k, M): Evaluate input M using private key k.
```
function, semantically i think it makes more sense to call this function Contribute as this conveys better what is happening, Evaluate() is less specific to the purpose of what is happening here.

**Comment by chris-wood** [comment]
Can you elaborate on why `Contribute` is more clear? As written, I don't agree.

**Comment by stef** [comment]
because in an OPRF two parties collaborate to calculate a value `c^s`. The client (c) blinds his value `c` using the blinding factor `r`, then sends over this blinded value to the server, who contributes his value `s` to the computation and returns it to the client. the client then unblinds the value from the server getting as a result `c^s`.

**Comment by stef** [comment]
on another note i would also rephrase "using private key k" to "using secret key k" as the usage of "private" suggest that there is also a public key associated with this, while there isn't. and as far as i can judge for this kind of usage it is more common to refer as secret and not private keys.

**Comment by chris-wood** [comment]
Use of “private key” matches terminology in the OPRF dependent document. Use of Evaluate is also a result of that document. I suggest filing an issue against that repository to consider Contribute.

**Comment by stef** [comment]
thanks will. do.

**Comment by chris-wood** [comment]
Closing based on the outcome of https://github.com/cfrg/draft-irtf-cfrg-voprf/issues/140.
