### ISSUE TITLE
Should the nonce length be a parameter?

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#58]
It's currently set 32 bytes, which may be too much (?) in some circumstances. However, adding yet another parameter that applications must choose is not great.

**Comment by kevinlewi** [comment]
I think it should be fine to keep this as 32 bytes, erroring on the side of safety without too much of a drawback.

**Comment by chris-wood** [comment]
I applied this directly on main. Closing.
