### ISSUE TITLE
Extraneous parameter pkS in CredentialResponse

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#63]
Why is it necessary to [put pkS in the CredentialResponse struct](https://github.com/cfrg/draft-irtf-cfrg-opaque/blame/master/draft-irtf-cfrg-opaque.md#L788)?

According to [this](https://github.com/cfrg/draft-irtf-cfrg-opaque/blame/master/draft-irtf-cfrg-opaque.md#L460-L464), pkS must be included within the envelope already. So, when the client parses the CredentialResponse struct, shouldn't it be able to obtain pkS from the envelope already?

**Comment by chris-wood** [comment]
That's a good question! I *think* it can probably be removed, but let's see what @hugokraw thinks?

**Comment by hugokraw** [comment]
I did not notice pkS is sent outside the envelope. Not only it would be redundant but pkS is the most important element to be authenticated as part of the envelope. Sending it outside may lead people to accept it without authentication.

**Comment by chris-wood** [comment]
Let's drop it. @kevinlewi, can you please prep a PR to do this?

**Comment by kevinlewi** [comment]
In light of the changes made in #102, this will need to be re-introduced again.
