### ISSUE TITLE
Why does FinalizeRequest take in idU as a parameter?

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#72]
According to [this](https://github.com/cfrg/draft-irtf-cfrg-opaque/blame/master/draft-irtf-cfrg-opaque.md#L651), idU is used to construct FinalizeRequest, despite it only being applicable if the application decides to include it in the Credentials struct: > "Applications may optionally include
> `pkU`, `idU`, or `idS` in the `Credentials.cleartext_credentials` structure, or in
> `Credentials.secret_credentials` if secrecy of these values is desired."

But if this is the case, then why not also make idS and pkU parameters to FinalizeRequest as well?

Same goes for RecoverCredentials. Either they should take in all of these optional parameters as inputs, or they should not include any of them.

**Comment by chris-wood** [comment]
Proposal: remove application-specific credential information from the parameter list, and call out to the application to build `Credentials` based on the server's `secret` and `cleartext` list.
