### ISSUE TITLE
Nail down AKE instantiations

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#77]
TLS 1.3 *is* the SIGMA-I instantiation, so I think we should drop this from the OPAQUE document. It's redundant, and will likely cause confusion between people who want to choose between one or the other. 

cc @kevinlewi

**Comment by hugokraw** [comment]
I don't agree with this one. It is important to show that OPAQUE can use any AKE protocol and 3DH/HMQV are of a very special type. In particular, signature-based protocols are always KCI-secure while KEM-based (and "implicitly authenticated") are not always. Moreover, if you go by efficiency and you do not want to use HMQV because of the patent, then SIGMA-I is more efficient than 3DH. These are illustrations of the protocol if you want to build it as standalone, not necessarily with TLS. Those building upon TLS are more likely to use the version based on exported authenticators than a 3-flow handshake. 
You can always choose 3DH as the must-to-implement protocol and leave SIGMA-I as optional.

**Comment by chris-wood** [comment]
I don't see any variant in the document as mandatory to implement. I see them as different flavors of AKEs that applications can choose to implement based on their needs. And I think that decision tree should look like the following:

- If we don't need signatures for authentication, use 3DH (or HMQV)
- If we do need signatures for authentication, use TLS 1.3 with OPAQUE

Currently, the decision tree is something like the following:

- If we don't need signatures for authentication, use 3DH
- If we do need signatures for authentication, use SIGMA-I or TLS 1.3 with OPAQUE. (How do we decide to use TLS 1.3 or SIGMA-I?)

The core of this issue is that I don't think it's best to introduce *yet another* AKE with the same shape as TLS 1.3.

**Comment by hugokraw** [comment]
I agree that there is no need to have a must-to-implement version other than for interoperability tests. But I am not sure that someone using a standalone implementation of OPAQUE will necessarily need all the complexities of TLS 1.3 to implement a simple OPAQUE-SIGMA version. An example of a protocol that would favor a signature-based instantiation that is not TLS 1.3 is IKEv2, although they would use SIGMA-R. Yet illustrating SIGMA-I in the document would help that case too.

**Comment by chris-wood** [comment]
So, as I see it, the delta between OPAQUE-SIGMA-I and TLS 1.3+OPAQUE is the wire format, not much more. If, however, we drop the "info" and additional fields (extensions) from OPAQUE-SIGMA-I, then there is a substantial difference. I would be in favor of keeping OPAQUE-SIGMA-I if it dropped extensions, because otherwise it's essentially TLS 1.3 but with a different wire format, and I don't think that rises to the level needed to specify yet another AKE.

**Comment by hugokraw** [comment]
I am not convinced that the complexity of implementing SIGMA-I with the info fields is same as implementing TLS 1.3. It may be the case if you understand the cryptography and system issues of TLS 1.3 well enough to just use the minimal skeleton that serves you in SIGMA-I. But how many such (real) experts are out there? Once we already define the flows for 3DH and HKDF, having them for SIGMA is no big deal. I am not sure that eliminating the SIGMA specific elements makes a huge difference.
And I am not sure that we will end defining a flavor of OPAQUE with TLS 1.3 that will use just the three handshake flows (as opposed to defining it with EA and 5 flows).

**Comment by chris-wood** [comment]
> It may be the case if you understand the cryptography and system issues of TLS 1.3 well enough to just use the minimal skeleton that serves you in SIGMA-I. But how many such (real) experts are out there? 

This is my key point: there are probably very few. I don't think it's wise to standardize something that the majority of folks may not understand when or how to use when the TLS 1.3 instantiation exists. 

> It may be the case if you understand the cryptography and system issues of TLS 1.3 well enough to just use the minimal skeleton that serves you in SIGMA-I. But how many such (real) experts are out there? 

That's a fair point! If the TLS WG decided to forgo all but the EA flow, then certainly there's a larger difference between SIGMA-I and TLS 1.3+OPAQUE. But if not, I think the delta between these two is small enough that it's not in the CFRG's (or IETF's) best interest to specify.

**Comment by chris-wood** [comment]
(Meta comment: perhaps we should just ask the list and see what they think?)

**Comment by hugokraw** [comment]
It has to be understood that these AKEs are "informational"/illustrative, not intended as full specifications. Having the unspecified/optional info fields makes it very clear that we are not providing a full specification. 

I am ok with raising this in the list.

**Comment by chris-wood** [comment]
> It has to be understood that these AKEs are "informational"/illustrative, not intended as full specifications. Having the unspecified/optional info fields makes it very clear that we are not providing a full specification.

Aha, well, that's the source of this disagreement! I was approaching this as a complete specification, as that allows us to provide test vectors. If it's incomplete, I'm not sure how we provide test vectors. This definitely seems like something that list should weigh in on. I'll craft a message!

**Comment by hugokraw** [comment]
You can produce test vectors that omit all optional fields. Or you can omit these optional fields from the specification as I just wrote in another thread and say in English that such elements may need to be transmitted by applications but we do not specify them as they will be application specific (we do say that they need to be included in the transcript).

**Comment by sayrer** [comment]
I saw the message on the list. I don't subscribe, so I'll comment here: a complete OPAQUE-3DH instantiation would be very helpful to me. BTW, the document is getting much easier for me to understand.

**Comment by chris-wood** [comment]
Closing as resolved, given #128 and #133. (SIGMA-I and HMQV will move to an appendix. We won't specify wire format specifics or provide test vectors, but we'll sketch how that could be done in future documents.)
