### ISSUE TITLE
Use of VOPRF should mention which mode is used

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#79]
Presumably we want to use the VOPRF with modeBase set (as opposed to modeVerifiable). But I could not find this mentioned anywhere in the spec in its current state

**Comment by chris-wood** [comment]
Yeah, it's the base mode. Do you want to take this and send a PR?

**Comment by chris-wood** [comment]
Fixed in #80. Closing.
