### ISSUE TITLE
Typo in 3DH key derivation

### ISSUE THREAD

**Issue by hugokraw** [cfrg/draft-irtf-cfrg-opaque#8]
The key K3dh needs to computed by the server as
 K3dh = ePubU^ePrivS | ePubU^PrivS | PubU^ePrivS
The current draft inverts the order between the last two elements making it inconsistent with the way the client computes the key.
(Reported by Kevin Lewi)

**Comment by hugokraw** [comment]
As you see my github skills improved significantly, but the truth I did
these postings guided by someone else :-)

Can I  address pull requests directly? DO you need to define me as
contributor? Or is it better that I let you push changes?


-- Hugo

Help build a *worldwide repository* of COVID-19 data
<https://iReport.algorand.org>, open to all, everywhere.

**Comment by chris-wood** [comment]
Ah, I forgot to add you as a contributor! Oops. Let me do that now.

**Comment by hugokraw** [comment]
Thanks. Also, add yourself as an author.

-- Hugo

Help build a *worldwide repository* of COVID-19 data
<https://iReport.algorand.org>, open to all, everywhere.
