### ISSUE TITLE
Remove RequestMetadata type

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#94]
This struct stores the scalar across Request/Finalize calls, which both happen on the client. There's no need to serialize or send this value on the wire anywhere, so we should just defer its representation to the underlying implementation. Given that the OPRF API is already a dependency we expose, I suggest we replace RequestMetadata with the actual type `Scalar`. 

While we're in here, we might also consider removing superfluous wrappers around OPRF types (like `RegistrationRequest` and `CredentialRequest`). 

@kevinlewi, what do you think?

**Comment by kevinlewi** [comment]
Sounds good to me. Just to be clear, none of the changes that you are referencing will actually affect the bytes being output by these functions, right? They are just syntactic changes to clean up the presentation if I am understanding correctly.

**Comment by chris-wood** [comment]
Well, partly. RequestMetadata contains a vector encoding of a scalar (so a serialized scalar prefixed by its length), but that's not really needed. What I'm suggesting is that we just output a scalar, e.g.:

```
CreateCredentialRequest(pwdU)

Input:
- pwdU, an opaque byte string containing the user's password

Output:
- request, an CredentialRequest structure
- r, an OPRF Scalar value

Steps:
1. (r, M) = Blind(pwdU)
2. Create CredentialRequest request with M
3. Output (request, r)
```

**Comment by kevinlewi** [comment]
Ah, got it. Yes, this makes sense, I believe in my implementation I already omitted the length prefix anyway.
