### ISSUE TITLE
Defining SerializeExtensions and DeserializeExtensions

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#97]
From [here](https://github.com/cfrg/draft-irtf-cfrg-opaque/blame/master/draft-irtf-cfrg-opaque.md#L444-L446): Don't these functions need to be defined somewhere? At least they should sort the extensions by their type, perhaps in increasing order. It seems defining these in the specification is a requirement to producing compatible test vectors.

cc: @chris-wood

**Comment by chris-wood** [comment]
> At least they should sort the extensions by their type, perhaps in increasing order.

Sorting isn't required, since each extension is identified by its type. That said, adding more detail so their implementation is clear wouldn't hurt.

**Comment by kevinlewi** [comment]
If one implementation decides to sort the credentials in increasing order, and another decides to sort the credentials in decreasing order, then they will end up with a different HMAC output. Our test vectors will pick some ordering in order to generate the HMAC, and so seemingly this ordering should be spelled out in the specification, right?

**Comment by chris-wood** [comment]
Ah, yeah, good point about different implementations. I’ll draft up a PR for this soon.

**Comment by chris-wood** [comment]
This is addressed by #107, which removes these credential serialize functions. The structs are already in wire format and don't need further serialization.

**Comment by chris-wood** [comment]
Closing as resolved.
